export const CREATE_POST = "POST/CREATE_POST"
export const FETCH_POSTS = "POST/FETCH_POSTS"
export const REQUEST_POSTS = "POST/REQUEST_POSTS" // saga
export const SHOW_LOADER = "APP/SHOW_LOADER"
export const HIDE_LOADER = "APP/HIDE_LOADER"
export const SHOW_ALERT = "APP/SHOW_ALERT"
export const HIDE_ALERT = "APP/HIDE_ALERT"
export const CREATE_COMMENT = "COMMENT/CREATE_COMMENT"
export const FETCH_COMMENT = "COMMENT/FETCH_COMMENT"

